# Generated by Django 3.1.5 on 2021-01-26 00:06

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Key features for this property', size=None, verbose_name='Key Features'),
        ),
    ]
